-- Rafta price tracking foundation
-- Apply in Supabase SQL Editor.
-- Safe to run multiple times: uses IF NOT EXISTS where possible.

-- 1) Persistent tracking/backoff state for products.
alter table public.urunler
  add column if not exists son_kontrol timestamptz,
  add column if not exists sonraki_kontrol timestamptz,
  add column if not exists hata_sayisi integer default 0,
  add column if not exists son_hata text,
  add column if not exists scrape_yontemi text,
  add column if not exists son_basarili_kontrol timestamptz,
  add column if not exists son_fiyat_num numeric,
  add column if not exists ilk_fiyat_num numeric;

-- 2) Price history numeric value. Keep existing string price too.
alter table public.fiyat_gecmisi
  add column if not exists fiyat_num numeric;

-- 3) Query performance for due-product worker.
create index if not exists idx_urunler_tracking_due
  on public.urunler (sonraki_kontrol, satin_alindi, guncelleme_istegi);

create index if not exists idx_urunler_email_active
  on public.urunler (email, satin_alindi);

-- 4) Notification dedupe: one notification per product/type/price.
create table if not exists public.bildirim_loglari (
  id bigint generated by default as identity primary key,
  urun_id bigint not null,
  email text,
  bildirim_tipi text not null,
  fiyat_num numeric,
  created_at timestamptz default now()
);

create unique index if not exists idx_bildirim_unique_price
  on public.bildirim_loglari (urun_id, bildirim_tipi, fiyat_num);

-- 5) Optional scrape run metrics for later admin monitoring.
create table if not exists public.scrape_runs (
  id bigint generated by default as identity primary key,
  started_at timestamptz default now(),
  finished_at timestamptz,
  checked_count integer default 0,
  success_count integer default 0,
  failure_count integer default 0,
  direct_count integer default 0,
  scraperapi_count integer default 0,
  playwright_count integer default 0
);
